repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: pretty-format-json
    exclude_types: [ jupyter ]
    args: [ --autofix ]
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-case-conflict
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.6.0
  hooks:
    - id: pyproject-fmt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.8
  hooks:
  - id: ruff
    args:
    - --fix
    - --preview
  - id: ruff-format
    args:
    - --preview
