FROM apache/airflow:slim-3.0.4-python3.12

WORKDIR /opt/airflow

COPY pyproject.toml requirements.txt ./

USER root
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir -r requirements.txt

COPY . /tmp/package
WORKDIR /tmp/package

RUN pip install -e .

WORKDIR /opt/airflow
